export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TARGETS_SUCCESS = 'GET_TARGETS_SUCCESS';
export const DELETE_TARGET_SUCCESS = 'DELETE_TARGET_SUCCESS';
export const CREATE_TARGET_SUCCESS = 'CREATE_TARGET_SUCCESS';
